name: base64
version: 0.5.0
author: warren.strange@gmail.com
description: A port of the Apache commons Base 64 codec to dart.
homepage: https://github.com/wstrange/base64
dependencies:
  unittest: any

